;Minimal version of default layout
;Minimal layout with less widgets

[bar/main]
width = 100%
height = 26pt
radius = 0
border-bottom-size = 2pt
border-color = ${colors.fg}
background = ${colors.bg}
foreground = ${colors.fg}
padding-left = 2
padding-right = 2
module-margin = 1
underline-size = 3
underline-color = ${colors.fg}

font-0 = "JetBrainsMono Nerd Font:style=Bold:size=11;3"
font-1 = "JetBrainsMono Nerd Font:style=Bold:size=15;4"

separator = |
separator-foreground = ${colors.alt}

modules-left = workspaces weather systray
modules-center = player-mpris
modules-right = bluetooth audio temperature date power

cursor-click = pointer
enable-ipc = true

