backend = "glx";
vsync = true;
shadow = false;
fading = false;

# ==========================================
#  BACKGROUND BLUR SYSTEM
# ==========================================
blur-background = true;

blur: {
  method = "dual_kawase";
  strength = 5;
};

# Prevent picom from blurring the screenshot selection utility
blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "class_g = 'slop'"
];

# ==========================================
#  CORNER ROUNDING SYSTEM
# ==========================================
corner-radius = 0;

rounded-corners-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "class_g = 'Polybar'",
    "class_g = 'polybar'"
];

round-borders = 1;
