[global]
frame_color = "#EBDBB2"
separator_color = frame

[urgency_low]
background = "#282828"
foreground = "#EBDBB2"

[urgency_normal]
background = "#282828"
foreground = "#EBDBB2"

[urgency_critical]
background = "#CC241D"
foreground = "#EBDBB2"
frame_color = "#FE8019"
