set $bg       #000000
set $fg       #D3D3D3
set $alt      #555555
# Window coloring rules
# class                 border  bground text    indicator child_border
client.focused          $fg     $bg     $fg     $fg       $fg
client.focused_inactive $alt    $bg     $fg     $alt      $alt
client.unfocused        $alt    $bg     $alt    $alt      $alt
client.urgent           $fg     $fg     $bg     $fg       $fg
