# Monochrome

set $bg    #000000
set $fg    #D3D3D3
set $alt   #555555
set $text  #D3D3D3
set $alert #FFFFFF

# class                 border  bground text   indicator child_border
client.focused          $fg     $bg     $text  $fg       $fg
client.focused_inactive $alt    $bg     $text  $alt      $alt
client.unfocused        $alt    $bg     $alt   $alt      $alt
client.urgent           $alert  $bg     $text  $alert    $alert
