# Gruvbox Alpine Barn

set $bg    #282828
set $fg    #ebdbb2
set $alt   #665C54
set $text  #EBDBB2
set $alert #CC241D

# Window coloring rules
# class                 border  bground text   indicator child_border
client.focused          $fg     $bg     $text  $fg       $fg
client.focused_inactive $alt    $bg     $text  $alt      $alt
client.unfocused        $alt    $bg     $alt   $alt      $alt
client.urgent           $alert  $bg     $text  $alert    $alert
