# Catppuccin Mocha

set $bg    #1E1E2E
set $fg    #B4BEFE
set $alt   #585B70
set $text  #CDD6F4
set $alert #F38BA8

# class                 border  bground text   indicator child_border
client.focused          $fg     $bg     $text  $fg       $fg
client.focused_inactive $alt    $bg     $text  $alt      $alt
client.unfocused        $alt    $bg     $alt   $alt      $alt
client.urgent           $alert  $bg     $text  $alert    $alert
