[global]
frame_color = "#ebdbb2"
separator_color = frame

[urgency_low]
background = "#282828"
foreground = "#ebdbb2"

[urgency_normal]
background = "#282828"
foreground = "#ebdbb2"

[urgency_critical]
background = "#cc241d"
foreground = "#ebdbb2"
frame_color = "#fe8019"
