foreground              #D0D0D0
background              #202020
selection_foreground    #232323
selection_background    #EECB8B

cursor                  #D0D0D0
cursor_text_color       #202020
url_color               #9E9E9E

active_border_color     #D0D0D0
inactive_border_color   #505050
bell_border_color       #AC4142

active_tab_foreground   #232323
active_tab_background   #EECB8B
inactive_tab_foreground #D0D0D0
inactive_tab_background #1A1A1A
tab_bar_background      #151515

color0                  #151515
color1                  #AC4142
color2                  #7E8D50
color3                  #E5B566
color4                  #6C99BA
color5                  #9E4E85
color6                  #7DD5CF
color7                  #D0D0D0
color8                  #505050
color9                  #AC4142
color10                 #7E8D50
color11                 #E5B566
color12                 #6C99BA
color13                 #9E4E85
color14                 #7DD5CF
color15                 #F5F5F5
