foreground              #D0D0D0
background              #101010
selection_foreground    #101010
selection_background    #E0E0E0

cursor                  #F5F5F5
cursor_text_color       #101010
url_color               #B8B8B8

active_border_color     #E8E8E8
inactive_border_color   #3A3A3A
bell_border_color       #B98286

active_tab_foreground   #101010
active_tab_background   #E8E8E8
inactive_tab_foreground #747474
inactive_tab_background #1C1C1C
tab_bar_background      #0A0A0A

color0                  #101010
color1                  #B98286
color2                  #D8DDD5
color3                  #C4C4C4
color4                  #888888
color5                  #9E9E9E
color6                  #B2B2B2
color7                  #D0D0D0
color8                  #505050
color9                  #D9A4A8
color10                 #F0F3EF
color11                 #E0E0E0
color12                 #A6A6A6
color13                 #B8B8B8
color14                 #CCCCCC
color15                 #FFFFFF
