# Everforest Garden

set $bg    #2B3339
set $fg    #A7C080
set $alt   #55635D
set $text  #D3C6AA
set $alert #E67E80

# Window coloring rules
# class                 border  bground text   indicator child_border
client.focused          $fg     $bg     $text  $fg       $fg
client.focused_inactive $alt    $bg     $text  $alt      $alt
client.unfocused        $alt    $bg     $alt   $alt      $alt
client.urgent           $alert  $bg     $text  $alert    $alert
