[global]
frame_color = "#A28DBD"
separator_color = frame

[urgency_low]
background = "#EAE4D1"
foreground = "#4B4652"

[urgency_normal]
background = "#EAE4D1"
foreground = "#4B4652"

[urgency_critical]
background = "#EAE4D1"
foreground = "#4B4652"
frame_color = "#B86474"
