# Auto-run crucial lightweight background utilities on boot
exec --no-startup-id polybar
exec_always --no-startup-id autotiling
exec --no-startup-id dunst
exec --no-startup-id feh --bg-solid '#111111'
exec --no-startup-id picom -b
exec_always --no-startup-id ~/.config/i3/scripts/setup-monitor.sh
exec --no-startup-id $startup_chat

# Fix standard mouse pointer tracking on empty workspace roots
exec_always --no-startup-id xsetroot -cursor_name left_ptr

exec_always --no-startup-id xrdb -merge ~/.Xresources

exec --no-startup-id nm-tray
exec --no-startup-id xfce4-clipman
exec --no-startup-id playerctld daemon
