# Lavender Light

set $bg    #EAE4D1
set $fg    #A28DBD
set $alt   #81788A
set $text  #4B4652
set $alert #B86474

# class                 border  bground text   indicator child_border
client.focused          $fg     $bg     $text  $fg       $fg
client.focused_inactive $alt    $bg     $text  $alt      $alt
client.unfocused        $alt    $bg     $alt   $alt      $alt
client.urgent           $alert  $bg     $text  $alert    $alert
