background            #262B22
foreground            #DCD7BA
cursor                #8DAA51
selection_background  #4D5A44
selection_foreground  #DCD7BA

color0                #262B22
color8                #4D5A44
color1                #D17A7A
color9                #E48B8B
color2                #8DAA51
color10               #A2C35D
color3                #D7B570
color11               #EBCB85
color4                #6A8D73  /* Changed from blue to a deep sage/bamboo */
color12               #7EA488
color5                #A88896  /* Warm muted plum instead of cold purple */
color13               #C09EB0
color6                #81A28A  /* Muted forest instead of aqua/cyan */
color14               #97BCA0
color7                #DCD7BA
color15               #F2EDD0
