# The directory where MPD will look for your music files.
music_directory     "/home/nobloat/Music"

# The directory where MPD will store its playlists.
playlist_directory  "/home/nobloat/.config/mpd/playlists"

# The file where MPD will store its database (library information).
db_file             "/home/nobloat/.config/mpd/database"

sticker_file        "/home/nobloat/.config/mpd/sticker.sql"

# The log file for MPD.
log_file            "/home/nobloat/.config/mpd/log"

# The PID file for MPD.
pid_file            "/home/nobloat/.config/mpd/pid"

# The file where MPD stores its current state (queue, etc.) on shutdown.
state_file          "/home/nobloat/.config/mpd/state"

auto_update "yes"


# Main audio output (PipeWire or PulseAudio)
audio_output {
    type "pipewire"
    name "My Pipewire Audio Output"
}

# Extra audio output for Cava visualizer
audio_output {
    type   "fifo"
    name   "my_fifo"
    path   "/tmp/mpd.fifo"
    format "44100:16:2"
}
