background #28242F
foreground #E6DFE9
selection_foreground    #3D3844
selection_background    #CFC3DB

cursor                  #9680B1
cursor_text_color       #F3EEE8
url_color               #876EA7

active_border_color     #A28DBD
inactive_border_color   #81788A
bell_border_color       #B86474

active_tab_foreground   #3D3844
active_tab_background   #B5A2CB
inactive_tab_foreground #605968
inactive_tab_background #DED5E3
tab_bar_background      #D7CEDB

color0                  #4B4652
color1                  #B85C6B
color2                  #6F927C
color3                  #A5804F
color4                  #6E82B7
color5                  #8C72A9
color6                  #5D8F94
color7                  #D0C8C1
color8                  #6B6373
color9                  #B86474
color10                 #82A990
color11                 #B9935B
color12                 #8095CB
color13                 #A98AC9
color14                 #70A5AA
color15                 #F3EEE8
