[global]
frame_color = "#b0b0b0"
separator_color = frame

[urgency_low]
background = "#1a1a1a"
foreground = "#d0d0d0"

[urgency_normal]
background = "#1a1a1a"
foreground = "#d0d0d0"

[urgency_critical]
background = "#1a1a1a"
foreground = "#ffffff"
frame_color = "#808080"
